services:
  devsu-client-db:
    image: postgres:18-alpine
    container_name: devsu-client-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data_db:/var/lib/postgresql
    networks:
      - devsu-fintech-network

  devsu-client-app:
    build: .
    container_name: devsu-client-app
    working_dir: /app
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    depends_on:
      - devsu-client-db # indicates to run first the db
      - devsu-client-queue
    networks:
      - devsu-fintech-network
  devsu-client-queue:
    image: rabbitmq:3.13-management-alpine
    container_name: devsu-client-queue
    ports:
      # Standar port for application communication (AMQP)
      - "5672:5672"
      # Web interface administration
      - "15672:15672"
    environment:
      # Develop credentials access
      RABBITMQ_DEFAULT_USER: ${RBQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RBQ_PASSWORD}
    volumes:
      # Data persistence to keep queue even if the container is down
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - devsu-fintech-network
networks:
  devsu-fintech-network:
volumes:
  rabbitmq_data: